In [1]:
from google.colab import drive
drive.mount('/content/gdrive', force_remount=True)

Mounted at /content/gdrive

In [6]:
path = '/content/gdrive/My Drive/NLP Engineer/Naive Bayes/Evade/'
path

'/content/gdrive/My Drive/NLP Engineer/Naive Bayes/Evade/'

## 1. Standardize our data

In [3]:
import pandas as pd

In [9]:
data = pd.read_excel(path + 'evade.xlsx', index_col=0)

In [10]:
data.head()

     Refund  Marital_Status  Taxable_Income  Evade
Tid
1         1               0          125000      0
2         0               1          100000      0
3         0               0           70000      0
4         1               1          120000      0
5         0               2           95000      1

In [11]:
data.tail()

     Refund  Marital_Status  Taxable_Income  Evade
Tid
6         0               1           60000      0
7         1               2          220000      0
8         0               0           85000      1
9         0               1           75000      0
10        0               0           90000      1

In [13]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10 entries, 1 to 10
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Refund          10 non-null     int64
 1   Marital_Status  10 non-null     int64
 2   Taxable_Income  10 non-null     int64
 3   Evade           10 non-null     int64
dtypes: int64(4)
memory usage: 400.0 bytes

In [14]:
data.shape

(10, 4)

In [15]:
data.columns

Index(['Refund', 'Marital_Status', 'Taxable_Income', 'Evade'], dtype='object')

In [16]:
data

     Refund  Marital_Status  Taxable_Income  Evade
Tid
1         1               0          125000      0
2         0               1          100000      0
3         0               0           70000      0
4         1               1          120000      0
5         0               2           95000      1
6         0               1           60000      0
7         1               2          220000      0
8         0               0           85000      1
9         0               1           75000      0
10        0               0           90000      1

In [17]:
data.shape[0]

10

In [18]:
data.shape[1]

4

In [20]:
data.columns[:-1]

Index(['Refund', 'Marital_Status', 'Taxable_Income'], dtype='object')

In [25]:
features = data[['Refund', 'Marital_Status', 'Taxable_Income']]
features

     Refund  Marital_Status  Taxable_Income
Tid
1         1               0          125000
2         0               1          100000
3         0               0           70000
4         1               1          120000
5         0               2           95000
6         0               1           60000
7         1               2          220000
8         0               0           85000
9         0               1           75000
10        0               0           90000

In [26]:
target = data['Evade']
target

Tid
1     0
2     0
3     0
4     0
5     1
6     0
7     0
8     1
9     0
10    1
Name: Evade, dtype: int64

## 2. Apply Naive Bayes

In [28]:
from sklearn.naive_bayes import GaussianNB
from sklearn.utils.validation import column_or_1d
#Create a Gaussian Classifier
model = GaussianNB()
#Train the model
model.fit(features, target) #column_or_1d(target)

GaussianNB(priors=None, var_smoothing=1e-09)

## 3. Check the Accuracy

In [34]:
import numpy as np
print("Prediction Accuracy is: ", model.score(features, target)*100, "%") #np.array(target)

Prediction Accuracy is:  100.0 %

In [35]:
model.classes_

array([0, 1])

>for Testing:


>**X_test_1 = [['No', 'Married', 120000], ['Yes', 'Divorce', 25000]]**

In [42]:
#Standardize the X_test_1
X_test_1 = [[0,1,120000], [1,2,25000]]

In [43]:
y_pred_1 = model.predict(X_test_1)
y_pred_1

array([0, 0])

In [50]:
#X_test_2 = [['Yes', 'Single', 180000], ['No', 'Single', 90000]]
#Standardize the X_test_2
X_test_2 = [[1,0,180000], [0,0,90000]]

In [51]:
y_pred_2 = model.predict(X_test_2)
y_pred_2

array([0, 1])

## 4. Save the Model

In [57]:
import pickle
pkl_evade = "evade_model.pkl" #filename
with open(pkl_evade, 'wb') as file:
  pickle.dump(model, file)

In [53]:
with open(pkl_evade, 'rb') as file:
  pkl_evade = pickle.load(file)

In [56]:
X_test = [[0,0,75000]]
y_pred = pkl_evade.predict(X_test)
y_pred

array([0])